# Generated by Django 4.1.7 on 2023-11-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.CharField(
                choices=[("S", "Student"), ("P", "Professional")],
                default="S",
                max_length=1,
            ),
        ),
    ]
