# Generated by Django 4.1.7 on 2023-11-10 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_industry_major_university"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="University",
            new_name="Institute",
        ),
    ]
