# Generated by Django 3.2.23 on 2024-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240101_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apikey',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
