# Generated by Django 4.1.7 on 2023-11-10 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_industry_name_alter_institute_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={"verbose_name_plural": "Industries"},
        ),
    ]
