# Generated by Django 4.1.7 on 2023-11-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_industry_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="university",
        ),
        migrations.AddField(
            model_name="user",
            name="institute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.institute",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.industry",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.major",
            ),
        ),
    ]
