# Generated by Django 4.1.7 on 2023-12-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_user_university_user_institute_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "model_name",
                    models.CharField(default="default_model_name", max_length=255),
                ),
                (
                    "model_id",
                    models.CharField(default="default_model_id", max_length=255),
                ),
            ],
        ),
    ]
